version: '3.3'
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    environment:
      PORT: 8000
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
     - /var/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: azurediamond
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: motiondb
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080